// WARNING: This output format is intended for human consumers only
// and is subject to change without notice. Knock yourself out.
fn main() -> () {
    let mut _0: ();
    let mut _1: bool;
    let mut _2: !;
    scope 1 {
        debug _i => const 0_usize;
    }

    bb0: {
        _1 = Not(const true);
        switchInt(move _1) -> [0: bb2, otherwise: bb1];
    }

    bb1: {
        _2 = core::panicking::panic(const "assertion failed: true") -> unwind continue;
    }

    bb2: {
        return;
    }
}
